from django.shortcuts import render

# Create your views here.
from .sub_views.login_page_view import login_page
from .sub_views.home_view import home_view
from .sub_views.registration_page_view import registration_page
from .sub_views.parameter_definition_view import parameter_definition_add,parameter_definition_list,parameter_definition_delete,parameter_definition_search,list_parameter_definition_lov,parameter_definition_list
from .sub_views.project_view import project_add,project_delete,project_list,project_search
from .sub_views.parameter_view import parameter_add,parameter_delete,parameter_list,parameter_search,load_units_type,load_system_short_name_equipment_name,load_equipment_short_name,export_parameters_csv
from .sub_views.parameter_definition_lov_view import parameter_definition_lov_add,parameter_definition_lov_list,parameter_definition_lov_delete,parameter_definition_lov_search,load_lov,parameter_definition_lov_cancel
from .sub_views.search_keywords import search_keywords,download_marked_pdf
from .sub_views.manage_pdfs import manage_pdfs
from .sub_views.export_csv import export_csv
from .sub_views.compare_pdfs import pdf_compare_view
from .sub_views.match_param_def import parameter_similarity_view
from .sub_views.parameter_analysis_view import parameter_analysis_view
from .sub_views.mrt_parameter_view import mrt_parameter_add,mrt_parameter_list,mrt_parameter_search,mrt_parameter_delete,mrt_parameter_master_list
from .sub_views.read_pdf import read_pdf,upload_pdf
from .sub_views.data_upload_script import data_upload_view
from .sub_views.read_pdf import read_pdf,upload_pdf,compare_prompt_with_pdf,clear_chat_history

